/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RapidPrototypingRouteImport } from './routes/rapid-prototyping'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as CustomMetalPartsRouteImport } from './routes/custom-metal-parts'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CncMachiningRouteImport } from './routes/cnc-machining'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R3dPrintingQuoteRouteImport } from './routes/3d-printing-quote'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrRapidPrototypingRouteImport } from './routes/gr.rapid-prototyping'
import { Route as GrCustomMetalPartsRouteImport } from './routes/gr.custom-metal-parts'
import { Route as GrCncMachiningRouteImport } from './routes/gr.cnc-machining'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'

const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidPrototypingRoute = RapidPrototypingRouteImport.update({
  id: '/rapid-prototyping',
  path: '/rapid-prototyping',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomMetalPartsRoute = CustomMetalPartsRouteImport.update({
  id: '/custom-metal-parts',
  path: '/custom-metal-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CncMachiningRoute = CncMachiningRouteImport.update({
  id: '/cnc-machining',
  path: '/cnc-machining',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dPrintingQuoteRoute = R3dPrintingQuoteRouteImport.update({
  id: '/3d-printing-quote',
  path: '/3d-printing-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrRapidPrototypingRoute = GrRapidPrototypingRouteImport.update({
  id: '/gr/rapid-prototyping',
  path: '/gr/rapid-prototyping',
  getParentRoute: () => rootRouteImport,
} as any)
const GrCustomMetalPartsRoute = GrCustomMetalPartsRouteImport.update({
  id: '/gr/custom-metal-parts',
  path: '/gr/custom-metal-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const GrCncMachiningRoute = GrCncMachiningRouteImport.update({
  id: '/gr/cnc-machining',
  path: '/gr/cnc-machining',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/portal': typeof PortalRoute
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/portal': typeof PortalRoute
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/portal': typeof PortalRoute
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
  id:
    | '__root__'
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dPrintingQuoteRoute: typeof R3dPrintingQuoteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CncMachiningRoute: typeof CncMachiningRoute
  CompanyRoute: typeof CompanyRoute
  CustomMetalPartsRoute: typeof CustomMetalPartsRoute
  EquipmentRoute: typeof EquipmentRoute
  FaqRoute: typeof FaqRoute
  ForumRoute: typeof ForumRoute
  PortalRoute: typeof PortalRoute
  RapidPrototypingRoute: typeof RapidPrototypingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  StartProjectRoute: typeof StartProjectRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  GrCncMachiningRoute: typeof GrCncMachiningRoute
  GrCustomMetalPartsRoute: typeof GrCustomMetalPartsRoute
  GrRapidPrototypingRoute: typeof GrRapidPrototypingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapid-prototyping': {
      id: '/rapid-prototyping'
      path: '/rapid-prototyping'
      fullPath: '/rapid-prototyping'
      preLoaderRoute: typeof RapidPrototypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-metal-parts': {
      id: '/custom-metal-parts'
      path: '/custom-metal-parts'
      fullPath: '/custom-metal-parts'
      preLoaderRoute: typeof CustomMetalPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnc-machining': {
      id: '/cnc-machining'
      path: '/cnc-machining'
      fullPath: '/cnc-machining'
      preLoaderRoute: typeof CncMachiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-printing-quote': {
      id: '/3d-printing-quote'
      path: '/3d-printing-quote'
      fullPath: '/3d-printing-quote'
      preLoaderRoute: typeof R3dPrintingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gr/rapid-prototyping': {
      id: '/gr/rapid-prototyping'
      path: '/gr/rapid-prototyping'
      fullPath: '/gr/rapid-prototyping'
      preLoaderRoute: typeof GrRapidPrototypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gr/custom-metal-parts': {
      id: '/gr/custom-metal-parts'
      path: '/gr/custom-metal-parts'
      fullPath: '/gr/custom-metal-parts'
      preLoaderRoute: typeof GrCustomMetalPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gr/cnc-machining': {
      id: '/gr/cnc-machining'
      path: '/gr/cnc-machining'
      fullPath: '/gr/cnc-machining'
      preLoaderRoute: typeof GrCncMachiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dPrintingQuoteRoute: R3dPrintingQuoteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CncMachiningRoute: CncMachiningRoute,
  CompanyRoute: CompanyRoute,
  CustomMetalPartsRoute: CustomMetalPartsRoute,
  EquipmentRoute: EquipmentRoute,
  FaqRoute: FaqRoute,
  ForumRoute: ForumRoute,
  PortalRoute: PortalRoute,
  RapidPrototypingRoute: RapidPrototypingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  StartProjectRoute: StartProjectRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  GrCncMachiningRoute: GrCncMachiningRoute,
  GrCustomMetalPartsRoute: GrCustomMetalPartsRoute,
  GrRapidPrototypingRoute: GrRapidPrototypingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
