/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RapidPrototypingRouteImport } from './routes/rapid-prototyping'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as CustomMetalPartsRouteImport } from './routes/custom-metal-parts'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CncMachiningRouteImport } from './routes/cnc-machining'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R3dPrintingQuoteRouteImport } from './routes/3d-printing-quote'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalOrderCodeRouteImport } from './routes/portal.$orderCode'
import { Route as GrRapidPrototypingRouteImport } from './routes/gr.rapid-prototyping'
import { Route as GrCustomMetalPartsRouteImport } from './routes/gr.custom-metal-parts'
import { Route as GrCncMachiningRouteImport } from './routes/gr.cnc-machining'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'
import { Route as AdminSchedulerRouteImport } from './routes/admin_.scheduler'
import { Route as AdminLiveRouteImport } from './routes/admin_.live'
import { Route as AdminFactoryRouteImport } from './routes/admin_.factory'
import { Route as AdminConfigRouteImport } from './routes/admin_.config'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RapidPrototypingRoute = RapidPrototypingRouteImport.update({
  id: '/rapid-prototyping',
  path: '/rapid-prototyping',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomMetalPartsRoute = CustomMetalPartsRouteImport.update({
  id: '/custom-metal-parts',
  path: '/custom-metal-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CncMachiningRoute = CncMachiningRouteImport.update({
  id: '/cnc-machining',
  path: '/cnc-machining',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R3dPrintingQuoteRoute = R3dPrintingQuoteRouteImport.update({
  id: '/3d-printing-quote',
  path: '/3d-printing-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOrderCodeRoute = PortalOrderCodeRouteImport.update({
  id: '/$orderCode',
  path: '/$orderCode',
  getParentRoute: () => PortalRoute,
} as any)
const GrRapidPrototypingRoute = GrRapidPrototypingRouteImport.update({
  id: '/gr/rapid-prototyping',
  path: '/gr/rapid-prototyping',
  getParentRoute: () => rootRouteImport,
} as any)
const GrCustomMetalPartsRoute = GrCustomMetalPartsRouteImport.update({
  id: '/gr/custom-metal-parts',
  path: '/gr/custom-metal-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const GrCncMachiningRoute = GrCncMachiningRouteImport.update({
  id: '/gr/cnc-machining',
  path: '/gr/cnc-machining',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulerRoute = AdminSchedulerRouteImport.update({
  id: '/admin_/scheduler',
  path: '/admin/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin_/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFactoryRoute = AdminFactoryRouteImport.update({
  id: '/admin_/factory',
  path: '/admin/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin_/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/factory': typeof AdminFactoryRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
  '/portal/$orderCode': typeof PortalOrderCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/factory': typeof AdminFactoryRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
  '/portal/$orderCode': typeof PortalOrderCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3d-printing-quote': typeof R3dPrintingQuoteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cnc-machining': typeof CncMachiningRoute
  '/company': typeof CompanyRoute
  '/custom-metal-parts': typeof CustomMetalPartsRoute
  '/equipment': typeof EquipmentRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/rapid-prototyping': typeof RapidPrototypingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/start-project': typeof StartProjectRoute
  '/track': typeof TrackRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin_/config': typeof AdminConfigRoute
  '/admin_/factory': typeof AdminFactoryRoute
  '/admin_/live': typeof AdminLiveRoute
  '/admin_/scheduler': typeof AdminSchedulerRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/gr/cnc-machining': typeof GrCncMachiningRoute
  '/gr/custom-metal-parts': typeof GrCustomMetalPartsRoute
  '/gr/rapid-prototyping': typeof GrRapidPrototypingRoute
  '/portal/$orderCode': typeof PortalOrderCodeRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/mcp'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/config'
    | '/admin/factory'
    | '/admin/live'
    | '/admin/scheduler'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
    | '/portal/$orderCode'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/mcp'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/config'
    | '/admin/factory'
    | '/admin/live'
    | '/admin/scheduler'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
    | '/portal/$orderCode'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/3d-printing-quote'
    | '/admin'
    | '/auth'
    | '/cnc-machining'
    | '/company'
    | '/custom-metal-parts'
    | '/equipment'
    | '/faq'
    | '/forum'
    | '/mcp'
    | '/portal'
    | '/rapid-prototyping'
    | '/sitemap.xml'
    | '/start'
    | '/start-project'
    | '/track'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin_/config'
    | '/admin_/factory'
    | '/admin_/live'
    | '/admin_/scheduler'
    | '/capabilities/$slug'
    | '/gr/cnc-machining'
    | '/gr/custom-metal-parts'
    | '/gr/rapid-prototyping'
    | '/portal/$orderCode'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3dPrintingQuoteRoute: typeof R3dPrintingQuoteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CncMachiningRoute: typeof CncMachiningRoute
  CompanyRoute: typeof CompanyRoute
  CustomMetalPartsRoute: typeof CustomMetalPartsRoute
  EquipmentRoute: typeof EquipmentRoute
  FaqRoute: typeof FaqRoute
  ForumRoute: typeof ForumRoute
  McpRoute: typeof McpRoute
  PortalRoute: typeof PortalRouteWithChildren
  RapidPrototypingRoute: typeof RapidPrototypingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  StartProjectRoute: typeof StartProjectRoute
  TrackRoute: typeof TrackRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminFactoryRoute: typeof AdminFactoryRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminSchedulerRoute: typeof AdminSchedulerRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  GrCncMachiningRoute: typeof GrCncMachiningRoute
  GrCustomMetalPartsRoute: typeof GrCustomMetalPartsRoute
  GrRapidPrototypingRoute: typeof GrRapidPrototypingRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapid-prototyping': {
      id: '/rapid-prototyping'
      path: '/rapid-prototyping'
      fullPath: '/rapid-prototyping'
      preLoaderRoute: typeof RapidPrototypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-metal-parts': {
      id: '/custom-metal-parts'
      path: '/custom-metal-parts'
      fullPath: '/custom-metal-parts'
      preLoaderRoute: typeof CustomMetalPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cnc-machining': {
      id: '/cnc-machining'
      path: '/cnc-machining'
      fullPath: '/cnc-machining'
      preLoaderRoute: typeof CncMachiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3d-printing-quote': {
      id: '/3d-printing-quote'
      path: '/3d-printing-quote'
      fullPath: '/3d-printing-quote'
      preLoaderRoute: typeof R3dPrintingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$orderCode': {
      id: '/portal/$orderCode'
      path: '/$orderCode'
      fullPath: '/portal/$orderCode'
      preLoaderRoute: typeof PortalOrderCodeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/gr/rapid-prototyping': {
      id: '/gr/rapid-prototyping'
      path: '/gr/rapid-prototyping'
      fullPath: '/gr/rapid-prototyping'
      preLoaderRoute: typeof GrRapidPrototypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gr/custom-metal-parts': {
      id: '/gr/custom-metal-parts'
      path: '/gr/custom-metal-parts'
      fullPath: '/gr/custom-metal-parts'
      preLoaderRoute: typeof GrCustomMetalPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gr/cnc-machining': {
      id: '/gr/cnc-machining'
      path: '/gr/cnc-machining'
      fullPath: '/gr/cnc-machining'
      preLoaderRoute: typeof GrCncMachiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/scheduler': {
      id: '/admin_/scheduler'
      path: '/admin/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AdminSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/live': {
      id: '/admin_/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/factory': {
      id: '/admin_/factory'
      path: '/admin/factory'
      fullPath: '/admin/factory'
      preLoaderRoute: typeof AdminFactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/config': {
      id: '/admin_/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalOrderCodeRoute: typeof PortalOrderCodeRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalOrderCodeRoute: PortalOrderCodeRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3dPrintingQuoteRoute: R3dPrintingQuoteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CncMachiningRoute: CncMachiningRoute,
  CompanyRoute: CompanyRoute,
  CustomMetalPartsRoute: CustomMetalPartsRoute,
  EquipmentRoute: EquipmentRoute,
  FaqRoute: FaqRoute,
  ForumRoute: ForumRoute,
  McpRoute: McpRoute,
  PortalRoute: PortalRouteWithChildren,
  RapidPrototypingRoute: RapidPrototypingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  StartProjectRoute: StartProjectRoute,
  TrackRoute: TrackRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminFactoryRoute: AdminFactoryRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminSchedulerRoute: AdminSchedulerRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  GrCncMachiningRoute: GrCncMachiningRoute,
  GrCustomMetalPartsRoute: GrCustomMetalPartsRoute,
  GrRapidPrototypingRoute: GrRapidPrototypingRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
