/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities': typeof CapabilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faq' | '/capabilities/$slug' | '/capabilities/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/capabilities/$slug' | '/capabilities'
  id: '__root__' | '/' | '/faq' | '/capabilities/$slug' | '/capabilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
